import Foundation

/// The Eve runtime conformer — EXPERIMENTAL / GATED.
///
/// `eve` (npm, verified v0.11.10) is a filesystem-first framework for durable
/// backend AI agents. Two hard facts make it unsafe to schedule from cron today:
///   1. It requires Node ≥ 24 (Cadence's host commonly has 22).
///   2. Its local run model is a long-running HTTP dev server; no one-shot,
///      fire-and-forget "run this agent and exit" command is verified.
/// So Cadence can scaffold Eve's (verified) file layout and offer Eve recipes,
/// but `RecipeInstaller` refuses to schedule it until the run command is proven.
/// The conformer exists so the abstraction genuinely covers both runtimes.
public struct EveRuntime: AgentRuntime {
    public init() {}

    public var id: RecipeRuntime { .eve }
    public var displayName: String { "Eve" }
    public var isExperimental: Bool { true }
    public var experimentalNote: String? {
        "Eve support is experimental: it needs Node ≥ 24 and a verified one-shot (cron-friendly) run command, which Cadence doesn't have yet."
    }

    // Eve uses the Vercel AI SDK gateway form; the dotted minor (4.6 vs Flue's
    // 4-6) is what Eve's docs show. Treat as needs-verify on first real run.
    public var suggestedModels: [String] { ["anthropic/claude-sonnet-4.6", "openai/gpt-5.4-mini", "xai/grok-4"] }
    public var defaultModel: String { "anthropic/claude-sonnet-4.6" }

    public func isProject(_ dir: URL) -> Bool {
        FileManager.default.fileExists(atPath: dir.appendingPathComponent("agent/agent.ts").path)
    }

    public func scaffoldWorkspaceIfNeeded(at dir: URL, provider: ModelProvider) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        if isProject(dir) { return }
        let pkg = """
        {
          "name": "cadence-eve-agents",
          "private": true,
          "type": "module",
          "engines": { "node": ">=24" },
          "dependencies": { "eve": "^0.11.10" }
        }
        """
        try? pkg.write(to: dir.appendingPathComponent("package.json"), atomically: true, encoding: .utf8)
        try fm.createDirectory(at: dir.appendingPathComponent("agent/tools"), withIntermediateDirectories: true)
        if let key = provider.envKeyName {
            try? "\(key)=\n".write(to: dir.appendingPathComponent(".env"), atomically: true, encoding: .utf8)
        }
    }

    public func agentEntrySource(slug: String, model: String, instructions: String) -> String {
        // Eve's agent definition lives in agent/agent.ts; the system prompt is a
        // sibling agent/instructions.md (written by the installer as a recipe file).
        """
        // Generated by Cadence — an Eve agent (EXPERIMENTAL).
        import { defineAgent } from 'eve';

        export default defineAgent({
          model: '\(model)',
        });
        """
    }

    public func setupCommand(for project: URL) -> String {
        "cd '\(project.path)' && npm install"
    }

    public func runCommand(project: URL, slug: String) -> String {
        // No verified one-shot/headless run command for cron — do NOT emit a
        // runnable line. The installer refuses experimental runtimes, so this
        // placeholder never reaches a crontab.
        "# Eve scheduling is disabled: no verified one-shot run command (needs Node ≥ 24)."
    }

    public func readiness(project: URL, slug: String, provider: ModelProvider) -> [ReadinessCheck] {
        [ReadinessCheck(name: "Runtime", passed: false,
                        detail: experimentalNote ?? "Eve is experimental.")]
    }
}
