import Foundation

/// Generates Flue agent source files and minimal project skeletons so Cadence
/// can create *new* model-backed agents and schedule them as local cron jobs —
/// a scheduled job whose logic is an LLM agent, not just a shell command.
public enum FlueScaffold {

    /// Curated, provider-prefixed model ids for the picker (Flue/Pi format).
    /// Defaults to the latest Claude models; users can override with free text.
    public static let suggestedModels: [String] = [
        "anthropic/claude-opus-4-8",
        "anthropic/claude-sonnet-4-6",
        "anthropic/claude-haiku-4-5",
        "anthropic/claude-fable-5",
    ]
    public static let defaultModel = "anthropic/claude-sonnet-4-6"

    /// The TypeScript source for a Flue agent.
    public static func agentSource(name: String, model: String, instructions: String) -> String {
        """
        // Generated by Cadence — a scheduled, model-backed agent.
        // Runs via: npx flue run \(name)
        //
        // Cadence integration (optional) — print these lines to stdout and Cadence records them:
        //   • Report cost:      CADENCE_USAGE {"model":"\(escapeSingle(model))","input_tokens":N,"output_tokens":N,"cost_usd":N}
        //   • Adapt schedule:   CADENCE_NEXT  {"cron":"0 */4 * * *"}   // or {"in_minutes":120}
        // The first shows up as per-run cost; the second offers a one-click "change cadence" in the app.
        import { createAgent } from '@flue/runtime';

        export default createAgent(() => ({
          model: '\(escapeSingle(model))',
          instructions: `\(escapeBacktick(instructions))`,
        }));
        """
    }

    public enum ScaffoldError: Error, CustomStringConvertible {
        case invalidName(String)
        case writeFailed(String)
        public var description: String {
            switch self {
            case .invalidName(let n): return "Invalid agent name “\(n)”. Use letters, numbers, and dashes."
            case .writeFailed(let m): return "Could not write agent file: \(m)"
            }
        }
    }

    /// A valid Flue agent identifier (kebab-ish, safe as a filename + CLI arg).
    public static func sanitize(name: String) -> String {
        let lowered = name.lowercased()
        let mapped = lowered.map { ch -> Character in
            (ch.isLetter || ch.isNumber) ? ch : "-"
        }
        var slug = String(mapped)
        while slug.contains("--") { slug = slug.replacingOccurrences(of: "--", with: "-") }
        return slug.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
    }

    /// Write an agent file into `<project>/agents/<name>.ts`. Returns its URL.
    @discardableResult
    public static func writeAgent(intoProject project: URL, name: String, model: String, instructions: String) throws -> URL {
        let slug = sanitize(name: name)
        guard !slug.isEmpty else { throw ScaffoldError.invalidName(name) }
        let agentsDir = project.appendingPathComponent("agents", isDirectory: true)
        do {
            try FileManager.default.createDirectory(at: agentsDir, withIntermediateDirectories: true)
            let fileURL = agentsDir.appendingPathComponent("\(slug).ts")
            try agentSource(name: slug, model: model, instructions: instructions)
                .write(to: fileURL, atomically: true, encoding: .utf8)
            return fileURL
        } catch {
            throw ScaffoldError.writeFailed("\(error.localizedDescription)")
        }
    }

    /// Create a minimal Flue project skeleton at `dir` if it isn't one already.
    /// Files only — the user still runs `npm install` once (we surface that).
    public static func scaffoldWorkspaceIfNeeded(at dir: URL, envKeys: [String] = ["ANTHROPIC_API_KEY"]) throws {
        let fm = FileManager.default
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        if FlueSource.isFlueProject(dir) { return }
        let name = dir.lastPathComponent

        // Pin the published beta versions: only 1.0.0-beta.* exist on npm, so a
        // "^1.0.0" range won't resolve. @flue/cli is a real dependency (not dev)
        // so its local `flue` bin is always installed and shadows the unrelated
        // Firebase package also published as bare `flue` on npx.
        let pkg = """
        {
          "name": "\(sanitize(name: name).isEmpty ? "cadence-agents" : sanitize(name: name))",
          "private": true,
          "type": "module",
          "engines": { "node": ">=22.19.0" },
          "dependencies": {
            "@flue/runtime": "1.0.0-beta.2",
            "@flue/cli": "1.0.0-beta.1"
          }
        }
        """
        // defineConfig is exported from the '@flue/cli/config' subpath — the
        // package has no root export, so importing from '@flue/cli' fails.
        let config = """
        // Generated by Cadence.
        import { defineConfig } from '@flue/cli/config';
        export default defineConfig({ target: 'node' });
        """
        let env = envKeys.isEmpty
            ? "# No API key required for this provider (local model).\n"
            : envKeys.map { "\($0)=" }.joined(separator: "\n") + "\n"
        try write(pkg, to: dir.appendingPathComponent("package.json"), overwrite: false)
        try write(config, to: dir.appendingPathComponent("flue.config.ts"), overwrite: false)
        try write(env, to: dir.appendingPathComponent(".env"), overwrite: false)
        try fm.createDirectory(at: dir.appendingPathComponent("agents"), withIntermediateDirectories: true)
    }

    /// The one-time setup command needed before a fresh workspace can run.
    public static func setupCommand(for project: URL) -> String {
        "cd \(shellQuote(project.path)) && npm install"
    }

    /// The env-var name Flue reads for a "provider/model" specifier's provider
    /// (nil for local/custom providers that need no key). Grounded in Flue's
    /// built-in provider catalog; `xai`/`anthropic` verified against the runtime.
    public static func providerEnvKey(forModelSpecifier model: String) -> String? {
        let provider = (model.split(separator: "/").first.map(String.init) ?? "").lowercased()
        switch provider {
        case "anthropic":             return "ANTHROPIC_API_KEY"
        case "xai":                   return "XAI_API_KEY"
        case "openai":                return "OPENAI_API_KEY"
        case "google", "gemini":      return "GEMINI_API_KEY"
        case "groq":                  return "GROQ_API_KEY"
        case "deepseek":              return "DEEPSEEK_API_KEY"
        case "mistral":               return "MISTRAL_API_KEY"
        case "openrouter":            return "OPENROUTER_API_KEY"
        case "ollama", "lmstudio", "custom": return nil
        default:                      return nil
        }
    }

    // MARK: - Helpers

    private static func write(_ contents: String, to url: URL, overwrite: Bool) throws {
        if !overwrite && FileManager.default.fileExists(atPath: url.path) { return }
        try contents.write(to: url, atomically: true, encoding: .utf8)
    }
    private static func escapeSingle(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "'", with: "\\'")
    }
    private static func escapeBacktick(_ s: String) -> String {
        s.replacingOccurrences(of: "\\", with: "\\\\")
         .replacingOccurrences(of: "`", with: "\\`")
         .replacingOccurrences(of: "$", with: "\\$")
    }
    private static func shellQuote(_ s: String) -> String {
        "'" + s.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
